<?php

namespace App\AI\Persistence;

use App\AI\DTO\AnalysisResult;
use App\AI\Metadata\AnalysisMetadata;
use App\AI\Serialization\AnalysisResultSerializer;
use App\Models\AiMetric;
use App\Models\Analysis;
use App\Models\AnalysisLog;
use App\Models\Meeting;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log; // remove after logging is no longer needed

/**
 * Persists a trusted AnalysisResult for a given Meeting.
 *
 * Trust boundary:
 *  - Input is an already-validated application-owned AnalysisResult
 *    (produced by StructuredAnalysisProcessor / FR-004).
 *  - Raw provider JSON is never accepted here.
 *  - The meeting association comes from the application-owned Meeting
 *    object, never from provider output.
 *
 * Atomicity:
 *  - Analysis is persisted first;
 *  - only after a successful persist is the Meeting marked COMPLETED;
 *  - the whole operation runs inside a database transaction, so a
 *    persistence failure rolls back and never leaves a false COMPLETED.
 */
final class AnalysisPersistenceService
{
    public function __construct(
        private readonly AnalysisResultSerializer $serializer = new AnalysisResultSerializer,
    ) {}

    public function persist(Meeting $meeting, AnalysisResult $result): Analysis
    {
        // TODO: Revert once testing is sufficient - remove temporary logging
        $this->log('[TEMP][AnalysisPersistenceService] persist() started', [
            'meeting_id' => $meeting->id,
        ]);

        return DB::transaction(function () use ($meeting, $result): Analysis {
            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Creating Analysis record (legacy)');
            $analysis = Analysis::create([
                'meeting_id' => $meeting->id,
                'result' => $this->serializer->toArray($result),
            ]);
            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Analysis created (legacy)', ['analysis_id' => $analysis->id]);

            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Updating meeting status to COMPLETED (legacy)');
            $meeting->update(['status' => 'COMPLETED']);
            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Meeting status updated (legacy)');

            return $analysis;
        });
    }

    /**
     * Persist a trusted AnalysisResult together with its safe analysis
     * metadata for a given Meeting, following the approved Option A model.
     *
     * Persistence layout (Option A):
     *  - analysis_logs : provider, model, prompt_version (→ prompt_templates),
     *    status, started_at, completed_at, error_category, error_message
     *  - analyses      : meeting_id (UNIQUE), result (jsonb),
     *    analysis_metadata (→ analysis_logs.id, UNIQUE)
     *  - ai_metrics    : analysis_id (UNIQUE), duration_ms (+ token columns)
     *
     * This is the FR-010 metadata-aware extension of {@see self::persist()}.
     * FR-005's {@see self::persist()} is intentionally left untouched.
     *
     * Trust / safety:
     *  - Metadata is an application-owned AnalysisMetadata value object
     *    (scalars only; no provider SDK types, keys, or raw payloads).
     *  - The meeting association still comes from the application-owned
     *    Meeting object, never from provider output.
     *  - The linked analysis_log FK is generated by the application, never
     *    chosen or overridden by provider output.
     *
     * Atomicity:
     *  - The analysis log, the Analysis row, the optional AI metrics row,
     *    and the Meeting COMPLETED transition are written in the same DB
     *    transaction. A failure anywhere rolls everything back, so a false
     *    COMPLETED can never be left behind (same semantics as FR-005).
     */
    public function persistWithMetadata(
        Meeting $meeting,
        AnalysisResult $result,
        AnalysisMetadata $metadata,
    ): Analysis {
        // TODO: Revert once testing is sufficient - remove temporary logging
        $this->log('[TEMP][AnalysisPersistenceService] persistWithMetadata() started', [
            'meeting_id' => $meeting->id,
            'provider' => $metadata->provider,
            'model' => $metadata->model,
            'schema_version' => $metadata->schemaVersion,
            'duration_ms' => $metadata->durationMs,
            'failure_category' => $metadata->failureCategory,
            'prompt_tokens' => $metadata->promptTokens,
            'completion_tokens' => $metadata->completionTokens,
            'total_tokens' => $metadata->totalTokens,
        ]);

        return DB::transaction(function () use ($meeting, $result, $metadata): Analysis {
            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Creating AnalysisLog');
            $log = AnalysisLog::create([
                'meeting_id' => $meeting->id,
                'status' => $metadata->failureCategory !== null ? 'FAILED' : 'COMPLETED',
                'provider' => $metadata->provider,
                'model' => $metadata->model,
                'prompt_version' => $metadata->schemaVersion,
                'error_category' => $metadata->failureCategory,
                'error_message' => null,
                'started_at' => $metadata->startedAt,
                'completed_at' => $metadata->completedAt,
            ]);
            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] AnalysisLog created', ['log_id' => $log->id]);

            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Creating Analysis record');
            $analysis = Analysis::create([
                'meeting_id' => $meeting->id,
                'result' => $this->serializer->toArray($result),
                'analysis_metadata' => $log->id,
            ]);
            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Analysis created', ['analysis_id' => $analysis->id]);

            if ($metadata->durationMs !== null) {
                // TODO: Revert once testing is sufficient - remove temporary logging
                $this->log('[TEMP][AnalysisPersistenceService] Creating AiMetric');
                AiMetric::create([
                    'analysis_id' => $analysis->id,
                    'prompt_tokens' => $metadata->promptTokens ?? 0,
                    'completion_tokens' => $metadata->completionTokens ?? 0,
                    'total_tokens' => $metadata->totalTokens ?? 0,
                    'duration_ms' => $metadata->durationMs,
                ]);
                // TODO: Revert once testing is sufficient - remove temporary logging
                $this->log('[TEMP][AnalysisPersistenceService] AiMetric created');
            }

            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Updating meeting status to COMPLETED');
            $meeting->update(['status' => 'COMPLETED']);
            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Meeting status updated');

            return $analysis;
        });
    }

    /**
     * Update an existing Analysis record with a new result and metadata.
     * Used for re-analysis where the meeting already has an analysis.
     */
    public function update(
        Analysis $analysis,
        AnalysisResult $result,
        AnalysisMetadata $metadata,
    ): Analysis {
        // TODO: Revert once testing is sufficient - remove temporary logging
        $this->log('[TEMP][AnalysisPersistenceService] update() started', [
            'analysis_id' => $analysis->id,
            'meeting_id' => $analysis->meeting_id,
            'provider' => $metadata->provider,
            'model' => $metadata->model,
            'failure_category' => $metadata->failureCategory,
        ]);

        return DB::transaction(function () use ($analysis, $result, $metadata): Analysis {
            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Creating AnalysisLog for update');
            $log = AnalysisLog::create([
                'meeting_id' => $analysis->meeting_id,
                'status' => $metadata->failureCategory !== null ? 'FAILED' : 'COMPLETED',
                'provider' => $metadata->provider,
                'model' => $metadata->model,
                'prompt_version' => $metadata->schemaVersion,
                'error_category' => $metadata->failureCategory,
                'error_message' => null,
                'started_at' => $metadata->startedAt,
                'completed_at' => $metadata->completedAt,
            ]);
            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] AnalysisLog created', ['log_id' => $log->id]);

            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Updating Analysis record');
            $analysis->update([
                'result' => $this->serializer->toArray($result),
                'analysis_metadata' => $log->id,
            ]);
            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Analysis updated');

            if ($metadata->durationMs !== null) {
                // TODO: Revert once testing is sufficient - remove temporary logging
                $this->log('[TEMP][AnalysisPersistenceService] Updating/Creating AiMetric');
                AiMetric::updateOrCreate(
                    ['analysis_id' => $analysis->id],
                    [
                        'prompt_tokens' => $metadata->promptTokens ?? 0,
                        'completion_tokens' => $metadata->completionTokens ?? 0,
                        'total_tokens' => $metadata->totalTokens ?? 0,
                        'duration_ms' => $metadata->durationMs,
                    ]
                );
                // TODO: Revert once testing is sufficient - remove temporary logging
                $this->log('[TEMP][AnalysisPersistenceService] AiMetric updated/created');
            }

            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Updating meeting status to COMPLETED');
            $analysis->meeting->update(['status' => 'COMPLETED']);
            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Meeting status updated');

            return $analysis;
        });
    }

    /**
     * Record a safe FAILED analysis log for a meeting, without creating any
     * trusted Analysis row. Used by the orchestrator on the failure path so
     * that diagnosis metadata (provider/model/version/timing/category) is
     * retained while no untrusted result is persisted.
     *
     * Safety:
     *  - error_message is always null (no raw provider text/secrets).
     *  - The failure category is an application-owned scalar.
     *  - The Meeting COMPLETED transition is intentionally NOT performed here.
     */
    public function recordFailure(Meeting $meeting, AnalysisMetadata $metadata): AnalysisLog
    {
        // TODO: Revert once testing is sufficient - remove temporary logging
        $this->log('[TEMP][AnalysisPersistenceService] recordFailure() started', [
            'meeting_id' => $meeting->id,
            'provider' => $metadata->provider,
            'model' => $metadata->model,
            'failure_category' => $metadata->failureCategory,
        ]);

        return DB::transaction(function () use ($meeting, $metadata): AnalysisLog {
            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] Creating FAILED AnalysisLog');
            // Original: return AnalysisLog::create([
            $log = AnalysisLog::create([
                'meeting_id' => $meeting->id,
                'status' => 'FAILED',
                'provider' => $metadata->provider,
                'model' => $metadata->model,
                'prompt_version' => $metadata->schemaVersion,
                'error_category' => $metadata->failureCategory,
                'error_message' => null,
                'started_at' => $metadata->startedAt,
                'completed_at' => $metadata->completedAt,
            ]);
            // TODO: Revert once testing is sufficient - remove temporary logging
            $this->log('[TEMP][AnalysisPersistenceService] FAILED AnalysisLog created', ['log_id' => $log->id]);

            return $log;
        });
    }

    /**
     * Safe logging that works in both web and test contexts.
     */
    private function log(string $message, array $context = []): void
    {
        try {
            if (class_exists(Log::class) && app()->bound('log')) {
                Log::info($message, $context);
            }
        } catch (\Throwable) {
            // Ignore logging failures in test contexts
        }
    }
}